trigger:
- main
- dev

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    python -m venv env
    source env/bin/activate
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    source env/bin/activate
    pytest tests/
  displayName: 'Run tests'
