name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-22.04  # Stabilität gewährleisten, kann auf ubuntu-24.04 geändert werden

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Aktualisiert auf die neueste Version

    - name: Set up Python
      uses: actions/setup-python@v4  # Aktualisiert auf v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Data Processing
      run: python scripts/data_processing.py

    - name: Train Model
      run: python scripts/train_model.py

    - name: Evaluate Model
      run: python scripts/evaluate_model.py

    - name: Upload Model
      uses: actions/upload-artifact@v4  # Aktualisiert auf v4 zur Vermeidung von Deprecation-Warnungen
      with:
        name: trained-model
        path: models/best_house_price_model.pkl

    - name: Cleanup
      run: rm -rf models/*.pkl  # Löscht das Modell lokal nach dem Upload, um Speicherplatz zu sparen

