name: ML Pipeline

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Data Processing
      run: python scripts/data_processing.py

    - name: Train Model
      run: python scripts/train_model.py

    - name: Evaluate Model
      run: python scripts/evaluate_model.py

   - name: Upload Model
  uses: actions/upload-artifact@v4
  with:
    name: trained-model
    path: models/best_house_price_model.pkl
